//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.36415
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardCustomizeTool.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DashboardCustomizeTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add Item に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddToolStripItem {
            get {
                return ResourceManager.GetString("AddToolStripItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Add Item に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddToolStripMenuItem {
            get {
                return ResourceManager.GetString("AddToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dashboard Customizer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configuration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialogTitle {
            get {
                return ResourceManager.GetString("ConfigDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Configuration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigToolStripMenuItem {
            get {
                return ResourceManager.GetString("ConfigToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Item に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeleteToolStripItem {
            get {
                return ResourceManager.GetString("DeleteToolStripItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Delete Item に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeleteToolStripMenuItem {
            get {
                return ResourceManager.GetString("DeleteToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditToolStripMenuItem {
            get {
                return ResourceManager.GetString("EditToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E&amp;xit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EndToolStripMenuItem {
            get {
                return ResourceManager.GetString("EndToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   equipment identifier name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EquipmentIdentNameText {
            get {
                return ResourceManager.GetString("EquipmentIdentNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The program cannot be started because the settings file is corrupt. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessage_Item_IniFile {
            get {
                return ResourceManager.GetString("ErrorMessage_Item_IniFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DashBoardCustomizeTool Already is running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageDouble {
            get {
                return ResourceManager.GetString("ErrorMessageDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export failure. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageExport {
            get {
                return ResourceManager.GetString("ErrorMessageExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Missing required DLL(s). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageFujiFlexaDll {
            get {
                return ResourceManager.GetString("ErrorMessageFujiFlexaDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import failure. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageImport {
            get {
                return ResourceManager.GetString("ErrorMessageImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The layout information could not be read because the layout information file is corrupt. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageLayoutIniFile {
            get {
                return ResourceManager.GetString("ErrorMessageLayoutIniFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The setting file and layout information file versions are different.
        ///Items that are not in the setting file will not be displayed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageLayoutIniFileDifference {
            get {
                return ResourceManager.GetString("ErrorMessageLayoutIniFileDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading of layout failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageOpen {
            get {
                return ResourceManager.GetString("ErrorMessageOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot save because the layout information file is corrupt. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageSaveLayout {
            get {
                return ResourceManager.GetString("ErrorMessageSaveLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save layout information file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageSaveLayoutFile {
            get {
                return ResourceManager.GetString("ErrorMessageSaveLayoutFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Export に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExportToolStripMenuItem {
            get {
                return ResourceManager.GetString("ExportToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileFToolStripMenuItem {
            get {
                return ResourceManager.GetString("FileFToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Layout information file|*.cfg に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileReadDlgFilter {
            get {
                return ResourceManager.GetString("FileReadDlgFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Import File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileReadDlgTitle {
            get {
                return ResourceManager.GetString("FileReadDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Export File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileSaveDlgTitle {
            get {
                return ResourceManager.GetString("FileSaveDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Import に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImportToolStripMenuItem {
            get {
                return ResourceManager.GetString("ImportToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   H に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayoutAreaHeightText {
            get {
                return ResourceManager.GetString("LayoutAreaHeightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overall size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayoutAreaSizeText {
            get {
                return ResourceManager.GetString("LayoutAreaSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   W に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayoutAreaWidthText {
            get {
                return ResourceManager.GetString("LayoutAreaWidthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quit Dashboard and continue work? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageDashboardEnd {
            get {
                return ResourceManager.GetString("MessageDashboardEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageExportComplete {
            get {
                return ResourceManager.GetString("MessageExportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageImportComplete {
            get {
                return ResourceManager.GetString("MessageImportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Will import layout. Any current layout will be discarded.
        ///Continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageImportLayout {
            get {
                return ResourceManager.GetString("MessageImportLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save the data first and then export. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageLayoutCfg {
            get {
                return ResourceManager.GetString("MessageLayoutCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading of the layout is completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageOpenComplete {
            get {
                return ResourceManager.GetString("MessageOpenComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save completed with equipment identification name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageSaveAsComplete {
            get {
                return ResourceManager.GetString("MessageSaveAsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A layout setting with the specified equipment identification name already exists.
        ///Do you want to overwrite? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageSaveAsExsistFile {
            get {
                return ResourceManager.GetString("MessageSaveAsExsistFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageSaveComplete {
            get {
                return ResourceManager.GetString("MessageSaveComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save current layout? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageSaveLayout {
            get {
                return ResourceManager.GetString("MessageSaveLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OkButtonText {
            get {
                return ResourceManager.GetString("OkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenDialogTitle {
            get {
                return ResourceManager.GetString("OpenDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenToolStripMenuItem {
            get {
                return ResourceManager.GetString("OpenToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save as equipment identifier name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveAsDialogTitle {
            get {
                return ResourceManager.GetString("SaveAsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save as equipment identifier name(&amp;A) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveAsToolStripMenuItem {
            get {
                return ResourceManager.GetString("SaveAsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveToolStripMenuItem {
            get {
                return ResourceManager.GetString("SaveToolStripMenuItem", resourceCulture);
            }
        }
    }
}
