//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.36415
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardCustomizeTool.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_zh_CHS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_zh_CHS() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DashboardCustomizeTool.Properties.Resources_zh-CHS", typeof(Resources_zh_CHS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   项目的追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddToolStripItem {
            get {
                return ResourceManager.GetString("AddToolStripItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   项目的追加(&amp;A) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddToolStripMenuItem {
            get {
                return ResourceManager.GetString("AddToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dashboard画面页面布局的变更工具 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   设置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialogTitle {
            get {
                return ResourceManager.GetString("ConfigDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   设置(&amp;O) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigToolStripMenuItem {
            get {
                return ResourceManager.GetString("ConfigToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   项目的删除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeleteToolStripItem {
            get {
                return ResourceManager.GetString("DeleteToolStripItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   项目的删除(&amp;D) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeleteToolStripMenuItem {
            get {
                return ResourceManager.GetString("DeleteToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   编辑(&amp;E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditToolStripMenuItem {
            get {
                return ResourceManager.GetString("EditToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   结束(&amp;X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EndToolStripMenuItem {
            get {
                return ResourceManager.GetString("EndToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   设施标识符名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EquipmentIdentNameText {
            get {
                return ResourceManager.GetString("EquipmentIdentNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   因为应用软件设定文件不正常，所以不能启动。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessage_Item_IniFile {
            get {
                return ResourceManager.GetString("ErrorMessage_Item_IniFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DashBoardCustomizeToolが既に起動しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageDouble {
            get {
                return ResourceManager.GetString("ErrorMessageDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   导出失败。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageExport {
            get {
                return ResourceManager.GetString("ErrorMessageExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   实行时必要的DLL不足。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageFujiFlexaDll {
            get {
                return ResourceManager.GetString("ErrorMessageFujiFlexaDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FujiFlexa的注册失败了。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageFujiFlexaLogon {
            get {
                return ResourceManager.GetString("ErrorMessageFujiFlexaLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   导入失败。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageImport {
            get {
                return ResourceManager.GetString("ErrorMessageImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   因为页面布局信息文件不正常，所以不能读入页面布局信息。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageLayoutIniFile {
            get {
                return ResourceManager.GetString("ErrorMessageLayoutIniFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   应用软件设定文件和页面布局信息文件的版本不同。
        ///不显示在应用软件设定文件中没有的项目。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageLayoutIniFileDifference {
            get {
                return ResourceManager.GetString("ErrorMessageLayoutIniFileDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   加载布局失败。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageOpen {
            get {
                return ResourceManager.GetString("ErrorMessageOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   因为页面布局信息文件不正常，保存失败了。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageSaveLayout {
            get {
                return ResourceManager.GetString("ErrorMessageSaveLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   无法保存布局信息文件。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageSaveLayoutFile {
            get {
                return ResourceManager.GetString("ErrorMessageSaveLayoutFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   导出(&amp;E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExportToolStripMenuItem {
            get {
                return ResourceManager.GetString("ExportToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文件(&amp;F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileFToolStripMenuItem {
            get {
                return ResourceManager.GetString("FileFToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   页面布局信息文件|*.cfg に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileReadDlgFilter {
            get {
                return ResourceManager.GetString("FileReadDlgFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   导入文件的选择 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileReadDlgTitle {
            get {
                return ResourceManager.GetString("FileReadDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   导出文件的选择 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileSaveDlgTitle {
            get {
                return ResourceManager.GetString("FileSaveDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   导入(&amp;I) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImportToolStripMenuItem {
            get {
                return ResourceManager.GetString("ImportToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   H に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayoutAreaHeightText {
            get {
                return ResourceManager.GetString("LayoutAreaHeightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   整体大小 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayoutAreaSizeText {
            get {
                return ResourceManager.GetString("LayoutAreaSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   W に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayoutAreaWidthText {
            get {
                return ResourceManager.GetString("LayoutAreaWidthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   结束Dashboard，持续作业吗？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageDashboardEnd {
            get {
                return ResourceManager.GetString("MessageDashboardEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   导出已完成。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageExportComplete {
            get {
                return ResourceManager.GetString("MessageExportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   导入完成。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageImportComplete {
            get {
                return ResourceManager.GetString("MessageImportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取入页面布局。
        ///是否可以废弃现有的页面布局？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageImportLayout {
            get {
                return ResourceManager.GetString("MessageImportLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   请在保存后实行导出。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageLayoutCfg {
            get {
                return ResourceManager.GetString("MessageLayoutCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   加载布局已完成。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageOpenComplete {
            get {
                return ResourceManager.GetString("MessageOpenComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   用设备标识名完成保存。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageSaveAsComplete {
            get {
                return ResourceManager.GetString("MessageSaveAsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   具有指定设备标识名称的布局设置已经存在。
        ///你想覆盖它吗？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageSaveAsExsistFile {
            get {
                return ResourceManager.GetString("MessageSaveAsExsistFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存完成。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageSaveComplete {
            get {
                return ResourceManager.GetString("MessageSaveComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   是否保存当前的页面布局？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageSaveLayout {
            get {
                return ResourceManager.GetString("MessageSaveLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OkButtonText {
            get {
                return ResourceManager.GetString("OkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   打开 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenDialogTitle {
            get {
                return ResourceManager.GetString("OpenDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   打开(&amp;O) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenToolStripMenuItem {
            get {
                return ResourceManager.GetString("OpenToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存为设备标识符名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveAsDialogTitle {
            get {
                return ResourceManager.GetString("SaveAsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存为设备标识符名称(&amp;A) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveAsToolStripMenuItem {
            get {
                return ResourceManager.GetString("SaveAsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存(&amp;S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveToolStripMenuItem {
            get {
                return ResourceManager.GetString("SaveToolStripMenuItem", resourceCulture);
            }
        }
    }
}
