//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.36415
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardCustomizeTool.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_jp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_jp() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DashboardCustomizeTool.Properties.Resource_jp", typeof(Resource_jp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   アイテムの追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddToolStripItem {
            get {
                return ResourceManager.GetString("AddToolStripItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アイテムの追加(&amp;A) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddToolStripMenuItem {
            get {
                return ResourceManager.GetString("AddToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dashboard画面レイアウト変更ツール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialogTitle {
            get {
                return ResourceManager.GetString("ConfigDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定(&amp;C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigToolStripMenuItem {
            get {
                return ResourceManager.GetString("ConfigToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アイテムの削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeleteToolStripItem {
            get {
                return ResourceManager.GetString("DeleteToolStripItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アイテムの削除(&amp;D) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeleteToolStripMenuItem {
            get {
                return ResourceManager.GetString("DeleteToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集(&amp;E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditToolStripMenuItem {
            get {
                return ResourceManager.GetString("EditToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了(&amp;X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EndToolStripMenuItem {
            get {
                return ResourceManager.GetString("EndToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設備識別子名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EquipmentIdentNameText {
            get {
                return ResourceManager.GetString("EquipmentIdentNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション設定ファイルが不正の為、起動できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessage_Item_IniFile {
            get {
                return ResourceManager.GetString("ErrorMessage_Item_IniFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DashBoardCustomizeToolが既に起動しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageDouble {
            get {
                return ResourceManager.GetString("ErrorMessageDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウトのエクスポートに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageExport {
            get {
                return ResourceManager.GetString("ErrorMessageExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実行に必要なDLLが不足しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageFujiFlexaDll {
            get {
                return ResourceManager.GetString("ErrorMessageFujiFlexaDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウトのインポートに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageImport {
            get {
                return ResourceManager.GetString("ErrorMessageImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウト情報ファイルが不正の為、レイアウト情報を読み込めません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageLayoutIniFile {
            get {
                return ResourceManager.GetString("ErrorMessageLayoutIniFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション設定ファイルとレイアウト情報ファイルのバージョンが違います。
        ///アプリケーション設定ファイルにないアイテムは表示されません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageLayoutIniFileDifference {
            get {
                return ResourceManager.GetString("ErrorMessageLayoutIniFileDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウトの読み込みに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageOpen {
            get {
                return ResourceManager.GetString("ErrorMessageOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウト情報ファイルが不正の為、保存に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageSaveLayout {
            get {
                return ResourceManager.GetString("ErrorMessageSaveLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウト情報ファイルの保存に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageSaveLayoutFile {
            get {
                return ResourceManager.GetString("ErrorMessageSaveLayoutFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エクスポート(&amp;E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExportToolStripMenuItem {
            get {
                return ResourceManager.GetString("ExportToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル(&amp;F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileFToolStripMenuItem {
            get {
                return ResourceManager.GetString("FileFToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウト情報ファイル|*.cfg に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileReadDlgFilter {
            get {
                return ResourceManager.GetString("FileReadDlgFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インポートファイルの選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileReadDlgTitle {
            get {
                return ResourceManager.GetString("FileReadDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エクスポートファイルの選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileSaveDlgTitle {
            get {
                return ResourceManager.GetString("FileSaveDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インポート(&amp;I) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImportToolStripMenuItem {
            get {
                return ResourceManager.GetString("ImportToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   H に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayoutAreaHeightText {
            get {
                return ResourceManager.GetString("LayoutAreaHeightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全体サイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayoutAreaSizeText {
            get {
                return ResourceManager.GetString("LayoutAreaSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   W に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayoutAreaWidthText {
            get {
                return ResourceManager.GetString("LayoutAreaWidthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dashboardを終了し、作業を続けますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageDashboardEnd {
            get {
                return ResourceManager.GetString("MessageDashboardEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エクスポートが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageExportComplete {
            get {
                return ResourceManager.GetString("MessageExportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インポートが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageImportComplete {
            get {
                return ResourceManager.GetString("MessageImportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウトを取り込みます。
        ///既存のレイアウトは破棄されますがよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageImportLayout {
            get {
                return ResourceManager.GetString("MessageImportLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存してからエクスポートを実行してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageLayoutCfg {
            get {
                return ResourceManager.GetString("MessageLayoutCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウトを読み込みました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageOpenComplete {
            get {
                return ResourceManager.GetString("MessageOpenComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設備識別名で保存が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageSaveAsComplete {
            get {
                return ResourceManager.GetString("MessageSaveAsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された設備識別名のレイアウト設定は既に存在します。
        ///上書きしますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageSaveAsExsistFile {
            get {
                return ResourceManager.GetString("MessageSaveAsExsistFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageSaveComplete {
            get {
                return ResourceManager.GetString("MessageSaveComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のレイアウトを保存しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageSaveLayout {
            get {
                return ResourceManager.GetString("MessageSaveLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OkButtonText {
            get {
                return ResourceManager.GetString("OkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenDialogTitle {
            get {
                return ResourceManager.GetString("OpenDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開く(&amp;O) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenToolStripMenuItem {
            get {
                return ResourceManager.GetString("OpenToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設備識別子名で保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveAsDialogTitle {
            get {
                return ResourceManager.GetString("SaveAsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設備識別子名で保存(&amp;A) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveAsToolStripMenuItem {
            get {
                return ResourceManager.GetString("SaveAsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存(&amp;S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveToolStripMenuItem {
            get {
                return ResourceManager.GetString("SaveToolStripMenuItem", resourceCulture);
            }
        }
    }
}
