//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace adWorkbookAddIn.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("adWorkbookAddIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;root&gt;
        ///    &lt;!-- 項目の表示・非表示の設定 --&gt;
        ///    &lt;DisplayControl&gt;
        ///        &lt;Value key=&quot;baseInfoLabel&quot; flag=&quot;1111111111&quot;/&gt;
        ///        &lt;Value key=&quot;checkItemNamePanel&quot; flag=&quot;1111111111&quot;/&gt;
        ///        &lt;Value key=&quot;currentValuePanel&quot; flag=&quot;0000110000&quot;/&gt;
        ///        &lt;Value key=&quot;customSettingsPanel&quot; flag=&quot;0111110100&quot;/&gt;
        ///        &lt;Value key=&quot;dateFormatPanel&quot; flag=&quot;0000001000&quot;/&gt;
        ///        &lt;Value key=&quot;detailSettingsLabel&quot; flag=&quot;0111110100&quot;/&gt;
        ///        &lt;Value key=&quot;displayCommentPanel&quot; flag=&quot;0001000000&quot;/&gt;
        ///        &lt;Value key=&quot;equipmentPanel [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CheckItemSettings {
            get {
                return ResourceManager.GetString("CheckItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap detacheck_80 {
            get {
                object obj = ResourceManager.GetObject("detacheck-80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap draw_80 {
            get {
                object obj = ResourceManager.GetObject("draw-80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap help_80 {
            get {
                object obj = ResourceManager.GetObject("help-80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap login_80 {
            get {
                object obj = ResourceManager.GetObject("login-80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap upload_80 {
            get {
                object obj = ResourceManager.GetObject("upload-80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap version_80 {
            get {
                object obj = ResourceManager.GetObject("version-80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap work_80 {
            get {
                object obj = ResourceManager.GetObject("work-80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   &lt;root&gt;
        ///    &lt;!-- コンボボックス定義 --&gt;
        ///    &lt;AdditionalInfoType&gt;
        ///        &lt;Value id=&quot;0&quot;&gt;&lt;/Value&gt;
        ///        &lt;Value id=&quot;1&quot;&gt;文字列&lt;/Value&gt;
        ///        &lt;Value id=&quot;2&quot;&gt;真理値&lt;/Value&gt;
        ///        &lt;Value id=&quot;3&quot;&gt;数値&lt;/Value&gt;
        ///        &lt;Value id=&quot;4&quot;&gt;実数&lt;/Value&gt;
        ///        &lt;Value id=&quot;5&quot;&gt;日付&lt;/Value&gt;
        ///        &lt;Value id=&quot;6&quot;&gt;IPv4アドレス&lt;/Value&gt;
        ///        &lt;Value id=&quot;7&quot;&gt;Macアドレス&lt;/Value&gt;
        ///        &lt;Value id=&quot;8&quot;&gt;プラグイン名&lt;/Value&gt;
        ///        &lt;Value id=&quot;9&quot;&gt;トレース情報&lt;/Value&gt;
        ///        &lt;Value id=&quot;10&quot;&gt;不良情報&lt;/Value&gt;
        ///    &lt;/AdditionalInfoType&gt;
        ///&lt;/root&gt;
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WorkSettings {
            get {
                return ResourceManager.GetString("WorkSettings", resourceCulture);
            }
        }
    }
}
