//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardCustomizeTool.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_jp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_jp() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DashboardCustomizeTool.Properties.Resource_jp", typeof(Resource_jp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   アイテムの追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddToolStripItem {
            get {
                return ResourceManager.GetString("AddToolStripItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アイテムの追加(&amp;A) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddToolStripMenuItem {
            get {
                return ResourceManager.GetString("AddToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dashboard画面レイアウト変更ツール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アイテムの削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeleteToolStripItem {
            get {
                return ResourceManager.GetString("DeleteToolStripItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アイテムの削除(&amp;D) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeleteToolStripMenuItem {
            get {
                return ResourceManager.GetString("DeleteToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集(&amp;E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditEToolStripMenuItem {
            get {
                return ResourceManager.GetString("EditEToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了(&amp;X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EndDToolStripMenuItem {
            get {
                return ResourceManager.GetString("EndDToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション設定ファイルが不正の為、起動できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessage_Item_IniFile {
            get {
                return ResourceManager.GetString("ErrorMessage_Item_IniFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DashBoardCustomizeToolが既に起動しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageDouble {
            get {
                return ResourceManager.GetString("ErrorMessageDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実行に必要なDLLが不足しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageFujiFlexaDll {
            get {
                return ResourceManager.GetString("ErrorMessageFujiFlexaDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウト情報ファイルが不正の為、レイアウト情報を読み込めません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageLayoutIniFile {
            get {
                return ResourceManager.GetString("ErrorMessageLayoutIniFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション設定ファイルとレイアウト情報ファイルのバージョンが違います。アプリケーション設定ファイルにないアイテムは表示されません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageLayoutIniFileDifference {
            get {
                return ResourceManager.GetString("ErrorMessageLayoutIniFileDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウト情報ファイルが不正の為、保存に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageSaveLayout {
            get {
                return ResourceManager.GetString("ErrorMessageSaveLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エクスポート(&amp;E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExportToolStripMenuItem {
            get {
                return ResourceManager.GetString("ExportToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル(&amp;F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileFToolStripMenuItem {
            get {
                return ResourceManager.GetString("FileFToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウト情報ファイル|*.cfg に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileReadDlgFilter {
            get {
                return ResourceManager.GetString("FileReadDlgFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インポートファイルの選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileReadDlgTitle {
            get {
                return ResourceManager.GetString("FileReadDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エクスポートファイルの選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileSaveDlgTitle {
            get {
                return ResourceManager.GetString("FileSaveDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インポート(&amp;I) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImportToolStripMenuItem {
            get {
                return ResourceManager.GetString("ImportToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dashboardを終了し、作業を続けますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageDashboardEnd {
            get {
                return ResourceManager.GetString("MessageDashboardEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウトを取り込みます。既存のレイアウトは破棄されますがよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageImportLayout {
            get {
                return ResourceManager.GetString("MessageImportLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存してからエクスポートを実行してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageLayoutCfg {
            get {
                return ResourceManager.GetString("MessageLayoutCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のレイアウトを保存しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageSaveLayout {
            get {
                return ResourceManager.GetString("MessageSaveLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存(&amp;S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveToolStripMenuItem {
            get {
                return ResourceManager.GetString("SaveToolStripMenuItem", resourceCulture);
            }
        }
    }
}
