
CREATE USER adfactory WITH PASSWORD 'adfactory' CREATEDB;
CREATE DATABASE "adFactoryDB2" WITH OWNER adfactory TEMPLATE="template0" ENCODING 'UTF8' LC_COLLATE 'C' LC_CTYPE 'C';
COMMENT ON DATABASE "adFactoryDB2" IS 'ver2.0.0';
