-- 対象テーブルのデータ削除
TRUNCATE TABLE log_stock RESTART IDENTITY;
TRUNCATE TABLE mst_bom RESTART IDENTITY;
TRUNCATE TABLE mst_location RESTART IDENTITY;
TRUNCATE TABLE mst_product RESTART IDENTITY;
TRUNCATE TABLE mst_stock RESTART IDENTITY;
TRUNCATE TABLE trn_delivery RESTART IDENTITY;
TRUNCATE TABLE trn_delivery_item RESTART IDENTITY;
TRUNCATE TABLE trn_material RESTART IDENTITY;
TRUNCATE TABLE trn_lot_trace RESTART IDENTITY;
